plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(syncLibs.plugins.kotlin.kapt)
    alias(syncLibs.plugins.sqldelight)
    alias(libs.plugins.license)
}

def flavors = [:]
try {
    apply from: 'flavors.gradle'
    flavors.putAll(addflavors)
} catch(UncheckedIOException ignored) {
    // Optional
}


android {
    namespace = "eu.pretix.pretixscan.droid"

    compileSdk = 36

    defaultConfig {
        applicationId "eu.pretix.pretixscan.droid"
        minSdk = 23
        targetSdk = 35
        versionCode = 117
        versionName = "3.4.2"
        vectorDrawables.useSupportLibrary = true
        vectorDrawables.generatedDensities = ['ldpi', 'mdpi', 'hdpi', 'xhdpi', 'xxhdpi']
        multiDexEnabled = true

        base.archivesName = rootProject.name + "-" + versionName
    }

    buildFeatures {
        buildConfig = true
        dataBinding = true
        viewBinding = true
    }

    kotlin {
        jvmToolchain {
            languageVersion.set(JavaLanguageVersion.of(17))
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled = true
    }

    signingConfigs {
        release {
            storeFile file("../../release.keystore")
            storePassword System.getenv("KSTOREPWD")
            keyAlias "pretixdroid"
            keyPassword System.getenv("KSTOREPWD")
        }
        flavors.each { flavorName, flavorData ->
            "$flavorName" {
                storeFile file("../../${flavorName}.keystore")
                storePassword System.getenv("KSTOREPWD")
                keyAlias "pretixdroid"
                keyPassword System.getenv("KSTOREPWD")
            }
        }
    }

    buildTypes {
		def sentry_dsn = ""
		try {
			Properties properties = new Properties()
			properties.load(project.rootProject.file('local.properties').newDataInputStream())
            sentry_dsn = properties.getProperty('sentry.dsn')
            if (sentry_dsn == null) {
                sentry_dsn = ""
            }
		} catch (ignore) {
		}

        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            multiDexKeepProguard = file('multidex-config.pro')
            manifestPlaceholders["SENTRY_DSN"] = sentry_dsn
        }
        debug {
            debuggable true
            applicationIdSuffix ".debug"
            versionNameSuffix "-debug"
            manifestPlaceholders["SENTRY_DSN"] = ""
        }
    }

    flavorDimensions "brand"
    productFlavors {
        pretix {
            dimension "brand"
            signingConfig = signingConfigs.release
        }
        flavors.each { flavorName, flavorData ->
            "$flavorName" {
                dimension "${flavorData['dimension']}"
                applicationId "${flavorData['appId']}"
                signingConfig = signingConfigs."$flavorName"
            }
        }
    }
    packagingOptions {
        resources {
            excludes += [
                'META-INF/DEPENDENCIES',
                'META-INF/LICENSE',
                'META-INF/LICENSE.txt',
                'META-INF/license.txt',
                'META-INF/NOTICE',
                'META-INF/NOTICE.txt',
                'META-INF/notice.txt',
                'META-INF/ASL2.0'
            ]
        }
    }

    lint {
        disable 'InvalidPackage', 'MissingTranslation'
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation uiLibs.androidx.appcompat
    implementation uiLibs.material
    implementation libs.androidx.legacy.support.v4
    implementation libs.androidx.vectordrawable
    implementation uiLibs.androidx.constraintlayout
    implementation libs.androidx.cardview
    implementation libs.androidx.recyclerview
    implementation libs.androidx.multidex
    implementation uiLibs.androidx.preferenceKtx
    implementation syncLibs.androidx.sqlite

    implementation libs.splitties.toast
    implementation libs.calendarview

    implementation syncLibs.okhttp
    implementation syncLibs.okhttp.tls
    implementation libs.sentry.android
    implementation libs.slf4j.nop
    implementation syncLibs.joda.time
    implementation syncLibs.sqlcipher.android
    implementation syncLibs.streamsupport.cfuture
    implementation syncLibs.jackson.databind
    implementation syncLibs.jackson.moduleKotlin
    implementation syncLibs.jackson.datatype.joda
    implementation syncLibs.eddsa
    implementation syncLibs.protobuf.javalite
    implementation syncLibs.sqldelight.android.driver

    // libpretixui
    implementation(project(':libpretixui-android')) {
        transitive = true
    }
    implementation uiLibs.glide
    coreLibraryDesugaring uiLibs.desugar.jdk.libs

    // libpretixsync
    implementation(project(':libpretixsync')) {
        transitive = false
    }

    // libpretixnfc
    implementation(project(':libpretixnfc')) {
        transitive = true
    }

    // libpretixnfc-android
    implementation(project(':libpretixnfc-android')) {
        transitive = true
    }

    implementation libs.kotlin.stdlib.jdk7
}

sqldelight {
    databases {
        SyncDatabase {
            packageName = "eu.pretix.pretixscan.sqldelight"

            dependency(project(":libpretixsync"))

            // Oldest dialect supported by SQLDelight 2.1.0
            // In Android projects, it will auto-select based on SDK
            // but not go lower than 3.18 (Android 9 is still on 3.8)
            dialect "app.cash.sqldelight:sqlite-3-18-dialect:${syncLibs.versions.sqldelight.get()}"
        }
    }
}
